### ISSUE TITLE
Permission for use of profile from @craftzdog

### ISSUE THREAD

**Issue by rackodo** [rackodo/py-github-gui#1]
Hi @craftzdog. Wanted to ask if you would be open to letting me use the output of your GitHub profile in my program as part of the documentation. I couldn't think of another way to contact you to ask.

- @rackodo.

<img width="632" alt="Screenshot 2023-04-14 at 8 31 23 am" src="https://user-images.githubusercontent.com/42397332/231897202-00e99c23-bf64-42f8-a03f-b56b59dc5c04.png">

**Comment by craftzdog** [comment]
ok

**Comment by rackodo** [comment]
Thank you!
